FROM python:3.9-slim
# Start from an official Python image
# Already has Python installed

WORKDIR /code
# All commands run inside /code folder

CMD ["python", "solution.py"]
# When container starts → run this command
# solution.py is the file we'll put there